### PR TITLE
Let the slider div render in a parent div of choosing

### PR DESCRIPTION
**Pull request by maikdiepenbroek**
This PR contains changes that fixes: #42

By adding ps-container attribute, the slider div get's rendered inside the parent div of choosing. 

Note that the parent div must contain: postion: relative for this to work. 

For now this only supports id's, should be able to expand it to support both classes and id's.

### CODE REVIEW

**Comment by dpiccone** [comment]
HI, I'd like to merge this, but unfortunately you changed the indentation to 2 spaces, and the whole commit is marked as a changed. Can you describe what did you change? Thanks.

**Comment by maikdiepenbroek** [comment]
Ill change the space indentation back to 4 spaces. Also i discovered a small bug. Will fix and then you can merge

**Comment by maikdiepenbroek** [comment]
Fixed indenting and the bug, unfortunately (for the PR) my IDE does remove the whitespace after the semicolon.

**Comment by maikdiepenbroek** [comment]
Any updates on merging this ?

**Comment by dpiccone** [comment]
Merged #44

**Pull request closed without merging**
