### PR TITLE
Move in effect

### PR DESCRIPTION
**Pull request by amirsabersharifi**
First of all thanks for your amazing directive. we needed to have the sliding effect a little bit more different in terms of how to show the content. so instead of just just popping out and display the content I changed your directive to have psMove attribute so that it literally moves the element from out of body to the body. I also added one example to the example and also updated the assertion test you had. There was also a missing section in html that I updated.

### CODE REVIEW

**Comment by dpiccone** [comment]
Hi, Thank you for the contribuition, I understand the effect, and I had different requests to have this kind of motion instead of the text popping in, and this will definitely be incorporated in the original directive, but I don't want to expand the API with ps-move.
Does it work when combined with ps-container?

**Comment by amirsabersharifi** [comment]
Thanks for reply. I will check on that ps-container. I am not sure about it. How do you want to incorporate that. I did ps-move as another effect because I noticed that you are have something similar for pushing the body. I think it might be good to introduce something like an effect and put the effect name in it so anyone can introduce different effects to library.

**Comment by amirsabersharifi** [comment]
@dpiccone I checked it out with container. Yup, it worked. Here is my plunker. https://plnkr.co/edit/vg1DnIt8MUljJgKBri9S?p=info
we can also set it as the default effect since visually it looks better

**Comment by dpiccone** [comment]
I have branched off v2 from your commits, you can check it at https://github.com/dpiccone/ng-pageslide/tree/v2 I plan to do some cleanup, merge this to master and release as v2

**Comment by dpiccone** [comment]
ref https://github.com/dpiccone/ng-pageslide/pull/123

**Pull request closed without merging**
