### PR TITLE
chore(slider): make functions for repeated manipulations

### PR DESCRIPTION
**Pull request by tmcgee123**
This is a proposed PR to clean up the file and make it a little more readable. I noticed that the setting of the body and slider style properties were repeated quite a bit. With the new functions, you are more versatile and test-able for future features.

CHANGES:
Cleaned up usage of double quotes to go towards JS best practices
of single quotes. Removed unused defaults variable, unneeded
expressions in the conditionals and extra object creation. Wrapped all branches in curly brackets
for best practice and consistency.

### CODE REVIEW

**Comment by tmcgee123** [comment]
@dpiccone any thoughts on this?

**Comment by dpiccone** [comment]
It does make the code more readable :+1: merged thanks!

**Comment by dpiccone** [comment]
I had to revert this commit because it was breaking some features like explained in #74

**Comment by tmcgee123** [comment]
I believe I just missed a line in the refactor, whoops! We probably need some more tests so we can refactor with confidence!

**Comment by dpiccone** [comment]
any help is welcome as time is always little for open source

**Pull request merged**
